### ISSUE TITLE
SDK not updated to 10074 yet

### ISSUE THREAD

**Issue by MikaelSoderstrom** [ms-iot/virtual-shields-universal#6]
I am using Visual Studio 2015 RC and Windows 10 Build 10074, but for some reason the SDK seems to be at Build 10069, even if you download the latest available.

When I am trying to open the projects (all three of them in the solution), it says I need to download an update for Visual Studio. When clicking on "Download" it just redirects me to http://www.microsoft.com, because the SDK is still not updated to 10074 (at least not public).

The solution for me was to change the build version back to 10069 in all three projects, and now I am able to open the project.

**Comment by MikaelSoderstrom** [comment]
Created a pull request: #7

**Comment by bryanschremp** [comment]
The Shield project still won't build. You have to change the build target to ARM. Once that is done, the build fails with multiple errors (Ignore the "2013" path, I am using VS 2015):
Severity	Code	Description	Project	File	Line
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\App.xaml.cs	56
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPage.xaml.cs	88
Error	CS0103	The name 'canvas' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPage.xaml.cs	149
Error	CS0103	The name 'canvas' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPage.xaml.cs	150
Error	CS0103	The name 'Display' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPage.xaml.cs	152
Error	CS0103	The name 'Display' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPage.xaml.cs	153
Error	CS0103	The name 'canvasBackground' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPage.xaml.cs	257
Error	CS0103	The name 'commandBar' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPage.xaml.cs	490
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	651
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	652
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	654
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	657
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	659
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	685
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	701
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	704
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	705
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	707
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	718
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	722
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	723
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	798
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	799
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	800
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	1033
Error	CS0103	The name 'player' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPageHandleMessage.cs	1037
Error	CS1061	'MainPage' does not contain a definition for 'text' and no extension method 'text' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	58
Error	CS1061	'MainPage' does not contain a definition for 'text' and no extension method 'text' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	63
Error	CS1061	'MainPage' does not contain a definition for 'canvas' and no extension method 'canvas' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	161
Error	CS1061	'MainPage' does not contain a definition for 'canvas' and no extension method 'canvas' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	165
Error	CS1061	'MainPage' does not contain a definition for 'player' and no extension method 'player' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	169
Error	CS1061	'MainPage' does not contain a definition for 'player' and no extension method 'player' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	170
Error	CS1061	'MainPage' does not contain a definition for 'canvas' and no extension method 'canvas' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	358
Error	CS1061	'MainPage' does not contain a definition for 'canvas' and no extension method 'canvas' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	379
Error	CS1061	'MainPage' does not contain a definition for 'canvas' and no extension method 'canvas' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	395
Error	CS1061	'MainPage' does not contain a definition for 'canvas' and no extension method 'canvas' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	424
Error	CS1579	foreach statement cannot operate on variables of type '?' because '?' does not contain a public definition for 'GetEnumerator'	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	426
Error	CS1061	'MainPage' does not contain a definition for 'canvas' and no extension method 'canvas' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	428
Error	CS1061	'MainPage' does not contain a definition for 'canvas' and no extension method 'canvas' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	435
Error	CS1579	foreach statement cannot operate on variables of type '?' because '?' does not contain a public definition for 'GetEnumerator'	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	437
Error	CS1061	'MainPage' does not contain a definition for 'canvas' and no extension method 'canvas' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\Services\Screen.cs	439
Error	CS1061	'SettingsPage' does not contain a definition for 'InitializeComponent' and no extension method 'InitializeComponent' accepting a first argument of type 'SettingsPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\SettingsPage.xaml.cs	57
Error	CS0103	The name 'connectList' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\SettingsPage.xaml.cs	77
Error	CS0103	The name 'connectList' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\SettingsPage.xaml.cs	79
Error		Data at the root level is invalid. Line 25, position 1.	Shield

**Comment by MikaelSoderstrom** [comment]
That's correct. Changing it to x86/x64 allows it to run on Windows 10.
